stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - build
  only:
    - main
  script:
    - cd /var/www/garanti-express.uz
    - git config --global --add safe.directory /var/www/garanti-express.uz
    - git pull
    - nvm i 20
    - npm run build
    - pm2 restart garanti-express.uz
