stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - build
  only:
    - main
  script:
    - git config --global user.name "$CI_GITLAB_USERNAME"
    - git config --global user.password "$CI_PERSONAL_ACCESS_TOKEN"
    - cd /var/www/garanti-express.uz
    - git reset --hard
    - git pull
    - npm install
    - npm run build
    - pm2 restart garanti-express.uz
